name: Sign APK

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate temporary keystore
        run: |
          keytool -genkeypair \
            -keystore release.jks \
            -storepass android \
            -keypass android \
            -alias github \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=GitHub,O=GitHub,C=NG"

      - name: Find Build Tools
        run: |
          echo "ZIPALIGN=$(find $ANDROID_HOME -name zipalign | head -1)" >> $GITHUB_ENV
          echo "APKSIGNER=$(find $ANDROID_HOME -name apksigner | head -1)" >> $GITHUB_ENV

      - name: Align APK
        run: |
          $ZIPALIGN -f app/HabitTracker-unsigned.apk aligned.apk

      - name: Sign APK
        run: |
          $APKSIGNER sign \
            --ks release.jks \
            --ks-key-alias github \
            --ks-pass pass:android \
            --key-pass pass:android \
            --out HabitTracker-signed.apk \
            aligned.apk

      - name: Verify APK
        run: |
          $APKSIGNER verify HabitTracker-signed.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: HabitTracker-Signed
          path: HabitTracker-signed.apk
